DROP TABLE IF EXISTS PRODUCTS;
CREATE TABLE PRODUCTS(
    ID INT  AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    PRICE DOUBLE(50) NOT NULL,
    INV INT NOT NULL,
    MAX INT NOT NULL,
    MIN INT NOT NULL
);
DROP TABLE IF EXISTS PARTS;
CREATE TABLE PARTS(
    ID INT  AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    PRICE DOUBLE(50) NOT NULL,
    INV INT NOT NULL,
    MAX INT NOT NULL,
    MIN INT NOT NULL,
    PRODUCT_ID INT
);